version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-top-api
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-latest:/data/db
  
  top_api:
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:300
    volumes:
      - ./.env:/opt/app/.env